map: "Pong-v0"

model_path: "./q_model"

max_episode_length: 6_000

action_repeat: 3

gama: 0.99

train:
  replay_memory_size: 10_000
  batch_run: 10 
  batch_size: 32
  replay_start_size: 2_000
  network_update_freq: 100
  episodes: 30
  ep:
    start: 1
    final: 0.1
    num_frames: 3_000
  debug:
    time: 10
  save_model_episode: 10

play:
  ep: 0.01
  render_time: 0.1
  debug:
    time: 1

image:
  history: 4
  skip: 2
  in_size: 84

ram:
  history: 2
  skip: 0
